name: Build ChestPlugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn -B clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChestPlugin
          path: target/*.jar
